### ISSUE TITLE
Didn't supply an ER diagram

### ISSUE THREAD

**Issue by Scifiler-sys** [220118-Reston-NET/TuanAnh-Nguyen-P0#1]
Didn't find an ER diagram. I'm not sure if you already made a database and just forgot to push a PNG file or you haven't done it

**Comment by kirasn** [comment]
Oh I did. It is "ERD.png" in the main folder

**Comment by kirasn** [comment]
Oh I see. You added this issue before I pushed the SQL version 😂 I only commit my code when I done something so 😂😂
